### ISSUE TITLE
readFully throws EOFException on certain GIFs

### ISSUE THREAD

**Issue by nietoperz809** [dragon66/animated-gif-reader#1]
... in line 610
count is then -1

**Comment by dragon66** [comment]
@nietoperz809 animated-gif-reader is not very tolerate about ill-structured images. The reason I used readFully is I found there is an issue with images in compressed file otherwise. The exception happens when the expected number of bytes is not fully read.

What is the purpose you use this reader? If you want to split the GIF into single frames, there is a way to do this from GIFTweaker.

If possible, you can put the image somewhere so that I can take a look.

Wen

**Comment by nietoperz809** [comment]
Hi, 
I need it for my image gallery: https://github.com/nietoperz809/JavaImageServer to create thumbnails. 
I use your reader because Java's ImageIO is much more intolerant of malformed GIFs.
Change "throw new EOFException();" into "return;", that makes it work.

:)

**Comment by dragon66** [comment]
@nietoperz809 happy to see it works now for you and also happy to see there is something less tolerant than my reader!
